<?php

namespace AppBundle\Repository;

/**
 * CorrigeCritereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CorrigeCritereRepository extends \Doctrine\ORM\EntityRepository
{
}
