<?php

namespace AppBundle\Repository;

/**
 * ModeCalculRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModeCalculRepository extends \Doctrine\ORM\EntityRepository
{
}
