<?php

namespace AppBundle\Repository;

/**
 * TypeCritereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeCritereRepository extends \Doctrine\ORM\EntityRepository
{
}
