<?php

namespace AppBundle\Repository;

/**
 * UserHasGroupeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserHasGroupeRepository extends \Doctrine\ORM\EntityRepository
{
}
