<?php

namespace AppBundle\Repository;

/**
 * UserHasEvaluationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserHasEvaluationRepository extends \Doctrine\ORM\EntityRepository
{
}
