<?php

namespace AppBundle\Repository;

/**
 * UserHasGroupeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserHasGroupeRepository extends \Doctrine\ORM\EntityRepository
{
    public function findGroupeByUser($id)
    {
        return $this->_em->createQuery(
            "
            SELECT DISTINCT d
            FROM AppBundle:UserHasGroupe h
            JOIN h.user u
            JOIN AppBundle:Groupe d
            WHERE u.id=$id AND h.groupe=d"
        );
    }

    public function findUserByGroupe($id)
    {
        return $this->_em->createQuery(
            "
            SELECT DISTINCT d
            FROM AppBundle:UserHasGroupe h
            JOIN h.groupe g
            JOIN AppBundle:User d
            WHERE g.id=$id AND h.user=d"
        );
    }
}
