<?php

namespace AppBundle\Repository;

/**
 * UserHasCoursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserHasCoursRepository extends \Doctrine\ORM\EntityRepository
{
    public function findCoursByUser($id)
    {
        return $this->_em->createQuery(
            "SELECT DISTINCT lesCours
            FROM AppBundle:UserHasCours h
            JOIN h.user user
            JOIN AppBundle:Cours lesCours
            WHERE user.id=$id AND h.cours=lesCours"
        );
    }

    public function findUserByCours($id)
    {
        return $this->_em->createQuery(
            "
            SELECT DISTINCT u
            FROM AppBundle:UserHasCours h
            JOIN h.cours d
            JOIN AppBundle:User u
            WHERE d.id=$id AND h.user=u"
        );
    }
}
