<?php

namespace AppBundle\Repository;

/**
 * UserHasEvaluationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserHasEvaluationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findUserHasEvaluationByUser($id)
    {
        return $this->_em->createQuery(
            "
            SELECT DISTINCT d
            FROM AppBundle:UserHasEvaluation h
            JOIN h.user u
            JOIN AppBundle:Evaluation d
            WHERE u.id=$id AND h.evaluation=d"
        );
    }
}
