<?php

namespace AppBundle\Repository;

/**
 * UserHasCoursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserHasCoursRepository extends \Doctrine\ORM\EntityRepository
{
}
