main:
    type: rest
    resource: 'AppBundle\Controller\DefaultController'

cours:
    type: rest
    resource: 'AppBundle\Controller\CoursController'
# A modifier suivant les bundles que l'on crééra.

users:
    type: rest
    resource: 'AppBundle\Controller\UserController'

