main:
    type: rest
    resource: 'AppBundle\Controller\DefaultController'

# A modifier suivant les bundles que l'on crééra.

cours:
    type: rest
    resource: 'AppBundle\Controller\CoursController'

coursHasGroupe:
    type: rest
    resource: 'AppBundle\Controller\CoursHasGroupeController'

groupe:
    type: rest
    resource: 'AppBundle\Controller\GroupeController'

users:
    type: rest
    resource: 'AppBundle\Controller\UserController'

userHasCours:
    type: rest
    resource: 'AppBundle\Controller\UserHasCoursController'

userHasGroupe:
    type: rest
    resource: 'AppBundle\Controller\UserHasGroupeController'

evaluations:
    type: rest
    resource: 'AppBundle\Controller\EvaluationController'

userHasEvaluations:
    type: rest
    resource: 'AppBundle\Controller\UserHasEvaluationController'