main:
    type: rest
    resource: 'AppBundle\Controller\DefaultController'

# A modifier suivant les bundles que l'on crééra.

users:
    type: rest
    resource: 'AppBundle\Controller\UserController'

