main:
    type: rest
    resource: 'AppBundle\Controller\DefaultController'

# A modifier suivant les bundles que l'on crééra.

cours:
    type: rest
    resource: 'AppBundle\Controller\CoursController'

groupe:
    type: rest
    resource: 'AppBundle\Controller\GroupeController'

users:
    type: rest
    resource: 'AppBundle\Controller\UserController'

userHasCours:
    type: rest
    resource: 'AppBundle\Controller\UserHasCoursController'

evaluations:
    type: rest
    resource: 'AppBundle\Controller\EvaluationController'