AppBundle\Entity\Categorie:
    type: entity
    table: categorie
    repositoryClass: AppBundle\Repository\CategorieRepository
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        description:
            type: string
            nullable: true
            length: 500
            options:
                fixed: false
        image:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
    lifecycleCallbacks: {  }
