AppBundle\Entity\Copie:
    type: entity
    table: copie
    repositoryClass: AppBundle\Repository\CopieRepository
    indexes:
        user_id:
            columns:
                - user_id
        section_id:
            columns:
                - section_id
        groupe_id:
            columns:
                - groupe_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        dateRendu:
            type: date
            nullable: true
            column: date_rendu
        note:
            type: decimal
            nullable: true
            precision: 10
            scale: 0
        fichier:
            type: string
            nullable: true
            length: 1000
            options:
                fixed: false
    manyToOne:
        user:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
        section:
            targetEntity: Section
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                section_id:
                    referencedColumnName: id
            orphanRemoval: false
        groupe:
            targetEntity: Groupe
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                groupe_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
