AppBundle\Entity\Correction:
    type: entity
    table: correction
    repositoryClass: AppBundle\Repository\CorrectionRepository 
    indexes:
        user_id:
            columns:
                - user_id
        copie_id:
            columns:
                - copie_id
        groupe_id:
            columns:
                - groupe_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        dateCorrection:
            type: date
            nullable: true
            column: date_correction
        fiabilite:
            type: decimal
            nullable: true
            precision: 10
            scale: 0
        note:
            type: decimal
            nullable: true
            precision: 10
            scale: 0
    manyToOne:
        user:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
        copie:
            targetEntity: Copie
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                copie_id:
                    referencedColumnName: id
            orphanRemoval: false
        groupe:
            targetEntity: Groupe
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                groupe_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
