AppBundle\Entity\Groupe:
    type: entity
    table: groupe
    repositoryClass: AppBundle\Repository\GroupeRepository
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
    lifecycleCallbacks: {  }
