AppBundle\Entity\Trapeze:
    type: entity
    table: trapeze
    repositoryClass: AppBundle\Repository\TrapezeRepository
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        point1:
            type: flooat
            nullable: true
        point2:
            type: float
            nullable: true
        point3:
            type: float
            nullable: true

        point4:
            type: integer
            nullable: true

    OneToOne:
        critere:
            targetEntity: Critere
            cascade: {  }
            fetch: LAZY
            inversedBy: null
            mappedBy: trapeze

    lifecycleCallbacks: {  }