AppBundle\Entity\TypeCritere:
    type: entity
    table: type_critere
    repositoryClass: AppBundle\Repository\TypeCritereRepository
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        type:
            type: string
            nullable: true
            options:
                unsigned: false
    lifecycleCallbacks: {  }
