AppBundle\Entity\UserHasGroupe:
    type: entity
    table: user_has_groupe
    repositoryClass: AppBundle\Repository\UserHasGroupeRepository
    indexes:
        user_id:
            columns:
                - user_id
        groupe_id:
            columns:
                - groupe_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    manyToOne:
        user:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
        groupe:
            targetEntity: Groupe
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                groupe_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
