AppBundle\Entity\User:
    type: entity
    table: user
    repositoryClass: AppBundle\Repository\UserRepository

    indexes:
        role_id:
            columns:
                - role_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        username:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        email:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        nom:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        prenom:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        password:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        image:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        fiabilite:
            type: float
            nullable: true
        moyenne:
            type: float
            nullable: true
    manyToOne:
        role:
            targetEntity: Role
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: role_id
            joinColumns:
                role_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
