AppBundle\Entity\UserHasCours:
    type: entity
    table: user_has_cours
    repositoryClass: AppBundle\Repository\UserHasCoursRepository
    indexes:
        user_id:
            columns:
                - user_id
        cours_id:
            columns:
                - cours_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    manyToOne:
        user:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
        cours:
            targetEntity: Cours
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                cours_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
