AppBundle\Entity\UserHasEvaluation:
    type: entity
    table: user_has_evaluation
    repositoryClass: AppBundle\Repository\UserHasEvaluationRepository
    indexes:
        user_id:
            columns:
                - user_id
        evaluation_id:
            columns:
                - evaluation_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    manyToOne:
        user:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
        evaluation:
            targetEntity: Evaluation
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                evaluation_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
